apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-loki
  namespace: monitoring
  labels:
    grafana_datasource: "1"
    app.kubernetes.io/name: grafana-datasource
    app.kubernetes.io/part-of: petclinic
    app.kubernetes.io/managed-by: kubectl
data:
  loki.yaml: |-
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki-gateway.monitoring.svc.cluster.local:80
        jsonData:
          maxLines: 1000
          httpHeaderName1: X-Scope-OrgID
        secureJsonData:
          httpHeaderValue1: fake
        isDefault: false
        editable: false
