apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: visits-service-prod
  namespace: argocd
  labels:
    app.kubernetes.io/name: visits-service
    app.kubernetes.io/part-of: petclinic
    app.kubernetes.io/managed-by: ArgoCD
    app.kubernetes.io/component: backend
spec:
  project: default
  source:
    repoURL: https://github.com/stephcloud/petclinic-platform.git
    targetRevision: main
    path: helm/petclinic-service
    helm:
      valueFiles:
        - ../../helm-values/visits-service.yaml
        - ../../helm-values/prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: petclinic-prod
