nameOverride: config-server
fullnameOverride: config-server
namespace: petclinic-dev

service:
  port: 8888

image:
  repository: 720035686687.dkr.ecr.eu-central-1.amazonaws.com/petclinic-dev/config-server
  tag: v1.0.0

labels:
  app.kubernetes.io/component: infrastructure

env:
  - name: SPRING_PROFILES_ACTIVE
    value: docker
  - name: MANAGEMENT_ENDPOINTS_WEB_BASEPATH
    value: /mgmt/act

probes:
  readiness:
    httpGet:
      path: /mgmt/act/health
      port: http
    initialDelaySeconds: 30
    periodSeconds: 10
  liveness:
    httpGet:
      path: /mgmt/act/health
      port: http
    initialDelaySeconds: 60
    periodSeconds: 15

initContainers: []
