apiVersion: v1
kind: ConfigMap
metadata:
  name: petclinic-config
  namespace: petclinic-dev
  labels:
    app.kubernetes.io/name: petclinic-config
    app.kubernetes.io/part-of: petclinic
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/component: infrastructure
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://petclinic-dev-mysql.ch40i6gwk9jk.eu-central-1.rds.amazonaws.com:3306/petclinic"
