apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openai-api-key
  namespace: petclinic-dev
  labels:
    app.kubernetes.io/name: openai-api-key
    app.kubernetes.io/part-of: petclinic
    app.kubernetes.io/managed-by: kubectl
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: openai-api-key
    creationPolicy: Owner
  data:
    - secretKey: api-key
      remoteRef:
        key: petclinic/dev/openai-api-key
